spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/jitpaydb
    username: jitpaydb
    password: jitpaydb
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    database: POSTGRESQL
    #    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    url: jdbc:postgresql://localhost:5432/jitpaydb
    schemas: public
    user: jitpaydb
    password: jitpaydb
    locations: classpath:db/migration